version: "3"
services:
  # Container
  hub:
    image: selenium/hub:4.0.0
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  # Container
  chrome:
    image: selenium/node-chrome:4.0.0
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4444
      - HUB_HOST=hub
    volumes:
      - ./Downloads:/home/seluser/Downloads
  # Container
  firefox:
    image: selenium/node-firefox:4.0.0
    shm_size: '512mb'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4444
      - HUB_HOST=hub
    volumes:
      - ./Downloads:/home/seluser/Downloads
  # Container
  google-search-module:
    image: virenderpannu/selenium-docker
    depends_on:
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=google-search-module.xml
    volumes:
      - ./output/google-search-result:/usr/share/learn/test-output
  # Container
  duckduckgo-search-module:
    image: virenderpannu/selenium-docker
    depends_on:
      - chrome
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=duckduckgo-search-module.xml
    volumes:
      - ./output/duckduckgo-search-result:/usr/share/learn/test-output
